### ISSUE TITLE
ID fields should have pipe delimited option

### ISSUE THREAD

**Issue by dsolovay** [estockwell-alpert/ContentExportTool#1]
Currently the option to return link fields as IDs returns them as semicolon delimited.

    {E71C307E-E643-4CB7-9EE1-36B71BA0D6BD}; {4A193968-B0FE-4E85-B058-5871296786AB}; {52095D02-0C29-47D7-9CEB-591525D17FAB}

 It would be helpful to have an option that returns the raw pipe delimited value:

    {E71C307E-E643-4CB7-9EE1-36B71BA0D6BD}|{4A193968-B0FE-4E85-B058-5871296786AB}|{52095D02-0C29-47D7-9CEB-591525D17FAB}

**Comment by estockwell-alpert** [comment]
[Content Export Tool 20191030.zip](https://github.com/estockwell-alpert/ContentExportTool/files/3789424/Content.Export.Tool.20191030.zip)

Added
