### ISSUE TITLE
Importing (or updating) item names with blank spaces

### ISSUE THREAD

**Issue by bunny-lajolla** [estockwell-alpert/ContentExportTool#10]
Hi Erica,
This is a great tool, thank you for taking the time to create it. 

I'm trying to create (or update) items that have blank spaces in the names, but I cannot get it to work. For example, for creation, I might have this csv:

```
Path, Name
/Home/folder-1/folder-2, name with spaces
```
But, the item will be created as "name-with-spaces" (no errors thrown)

Similarly, if I try and update the created item to remove the hyphens using (with or without quotes)
```
Path, Name
/Home/folder-1/folder-2/name-with-spaces, "name with spaces"
```
the tool will indicate success but the update doesn't actually happen.  

Am I doing something wrong here, or is this just not possible? I appreciate that spaces are not a great idea in Sitecore item names but we do have a few places where we would need to use them. 

Thanks!

**Comment by estockwell-alpert** [comment]
That sounds like a matter of how your Sitecore instance is configured. The import tool does not make any transformations on the name. If you create a new item manually in Sitecore with spaces in the name, does it change the spaces to hyphens?

You cannot change the Name of the item in the import. The Name column will not do anything on update

**Comment by bunny-lajolla** [comment]
Hi Erica, 

Thanks for coming back - just confirmed that we can manually create items with spaces in the name without any problems, and can also update items to have spaces in the name.

**Comment by bunny-lajolla** [comment]
Hi again Erica, 

It may be something to do with the fact that I'm trying to insert items based on a Branch Template, but using their underlying template type. I'll dig into this some more tomorrow.

**Comment by bunny-lajolla** [comment]
Hi Erica - you are right, it does seem like its our configuration, sorry for the trouble. I'll close this one off.

**Comment by estockwell-alpert** [comment]
@bunny-lajolla Great, thanks for letting me know!
