### ISSUE TITLE
Export is changing the characters instead of exporting the field value in db as is

### ISSUE THREAD

**Issue by vrkmajeti** [estockwell-alpert/ContentExportTool#2]
Following are few field value alterations during the process. Any alteration/deviation from the expected behavior should be performed through user choice selection ideally.
1. [ContentExport.aspx.cs#L1467](https://github.com/estockwell-alpert/ContentExportTool/blob/c6495567881fa5c9ad50c5ea71e3c44703947e28/ContentExport.aspx.cs#L1467) -> It should not have included  `Replace("<br/>", string.Empty).Replace("<br />", string.Empty)` unexpectedly and export different/wrong field value from the database without user's choice.
2. [ContentExport.aspx.cs#L1301](https://github.com/estockwell-alpert/ContentExportTool/blob/c6495567881fa5c9ad50c5ea71e3c44703947e28/ContentExport.aspx.cs#L1301) -> Arabic text  in database `على لسان جفرا ناصر: "العمل وتربية أطفالي بمفردي في غزة كان شاقًا، لكن لا يمكن وصف صعوبة القيام بذلك تحت القصف"` . But, exported `على لسان جفرا ناصر: ""العمل وتربية أطفالي بمفردي في غزة كان شاقًا، لكن لا يمكن وصف صعوبة القيام بذلك تحت القصف""`. Unexpected change in export process is that it converted one double quote into two double quotes instead of exporting the database value as is. This is probably done to comply with csv. So, Can content export export to xslx file instead?

**Comment by estockwell-alpert** [comment]
With the second issue, does this ONLY happen with Arabic text? Can you test is with English text? I'll try to test it on my end.

The tool does not currently support xslx, only csv. This is in my To Do list but I don't have any estimate of when it will be released. 

For any of these issues, feel free to work on them yourselves and open a pull request.

**Comment by estockwell-alpert** [comment]
I've uploaded a new release that should fix these two bugs
https://github.com/estockwell-alpert/ContentExportTool/releases/tag/8.4.4
