### ISSUE TITLE
Language version not created on an existing item if it's a fallback version

### ISSUE THREAD

**Issue by kningyi** [estockwell-alpert/ContentExportTool#3]
Hi there,

I have an item that I want to update (I don't want to create a new item).

This item only has EN and EN-US version, and I test Content Import to add an EN-GB version with some field values.

However, the EN-GB version of the item still fallbacks to its EN version, and there isn't any version created. 

Isn't content import supposed to create a new version with the imported values if no language version is found?

**Comment by estockwell-alpert** [comment]
Yes, it should create a new version. Do you have the Language column with en-GB specified as the language?

**Comment by estockwell-alpert** [comment]
This appears to be an issue when Fallback language is enabled, because Item.Versions.Count > 0 when language fallback is enabled, so it's not creating a new version. I will have a fix for this shortly

**Comment by estockwell-alpert** [comment]
This has been fixed in the latest release https://github.com/estockwell-alpert/ContentExportTool/releases/tag/8.5

**Comment by kningyi** [comment]
Thanks!

But the package did not have the fix, I've manually updated it with your latest ContentExport.aspx/ ContentExport.aspx.cs / ContentExport.aspx.designer.cs files
