### ISSUE TITLE
Created and updated between filters aren't working

### ISSUE THREAD

**Issue by vrkmajeti** [estockwell-alpert/ContentExportTool#4]
There is a 2021 year folder. Inside that folder, there is 12 month folder. Inside that, there are multiple news items created during december. 
1. Get All Language Versions checkbox: Checked
2. If we don't select any date filter, all child items of 12 folder are exporting fine. if we select date filter 12/01/2021 and 12/31/2021, none of those child items creaed in december are exporting. This is happening especially when content existing in spanish only.
![image](https://user-images.githubusercontent.com/1881988/149731867-b2c26809-c790-4dba-ae06-3a841f0538c8.png)

**Comment by estockwell-alpert** [comment]
Do the items have English versions or only Spanish? What are the created/updated dates for the English versions? What happens if you select Spanish only?

**Comment by estockwell-alpert** [comment]
I've released an update to check the selected language version(s) in the date filtering. Please update with the latest release and try your export https://github.com/estockwell-alpert/ContentExportTool/releases/tag/8.6

**Comment by vrkmajeti** [comment]
> Do the items have English versions or only Spanish? What are the created/updated dates for the English versions? What happens if you select Spanish only?

website default language is spanish. Items had spanish version only. no english versions. but, we selected the checkbox for "Get All language versions". Also tried the "Spanish" langauge in dropdown. Same issue. no results in export.

**Comment by vrkmajeti** [comment]
> I've released an update to check the selected language version(s) in the date filtering. Please update with the latest release and try your export https://github.com/estockwell-alpert/ContentExportTool/releases/tag/8.6

Appreciate the fix @estockwell-alpert. This is working now.
