### ISSUE TITLE
Feature request - Is there anyway to export isPublished boolean flag when exporting from master database?

### ISSUE THREAD

**Issue by vrkmajeti** [estockwell-alpert/ContentExportTool#5]
Is there anyway to export isPublished boolean flag when exporting from master database?

If parent folder is draft workflow state and all children are in final approved workflows state, those child items won't be published/live because parent is not live. So, we have been using following powershell command to know if item exists in web db to understand that item was published. 

Unfortunately, even though item's language version is published and exists in web db, we are getting null return value some times when using the following script. but works most of the time.
$langVerWeb = Get-Item -Path web: -ID $Item.ID -Language $Item.Language.Name -ErrorAction SilentlyContinue 
$isPublished = $langVerWeb -ne $null
Could you please try to provide export of IsPublished flag value per itemID and langauge, when exporting from master database?

**Comment by estockwell-alpert** [comment]
Yes, I can add a feature for this soon

**Comment by estockwell-alpert** [comment]
Feature has been added in the latest release: https://github.com/estockwell-alpert/ContentExportTool/releases/tag/8.7

**Comment by vrkmajeti** [comment]
@estockwell-alpert -
Because each language latest version of item could be published or not published independently, Can we ensure that this reports different isPublished flag value per each of the item.Languages
https://github.com/estockwell-alpert/ContentExportTool/commit/14483565ee84b52af2c19353dc90786d55e86d20#r64200526

**Comment by estockwell-alpert** [comment]
This has been updated in the latest release, 8.8
