### ISSUE TITLE
Cannot clear Link fields through import

### ISSUE THREAD

**Issue by jwetmorevelir** [estockwell-alpert/ContentExportTool#8]
When trying to remove content from a general link field I needed to provide an empty link value (<link url="" />) because an empty field  was not imported.  It would be great to be able to remove the value from a link field with the import functionality.  This issue occurred using the version: Content.Export.Tool.for.Azure.9.2.20230327

**Comment by estockwell-alpert** [comment]
This has been fixed in the [latest release](https://github.com/estockwell-alpert/ContentExportTool/releases/tag/9.2)
