### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by arunraj777** [estockwell-alpert/ContentExportTool#9]
When we are trying to export same item with different language, it is not working as expected. For example, when i am trying for Russians or Portuguese languages, those are not exporting same value as Sitecore content. instead of that it is giving some different characters

**Comment by estockwell-alpert** [comment]
@arunraj777 can you provide a screenshot? It is likely because the characters you have in Sitecore are not supported by Excel. See [https://ericastockwellalpert.wordpress.com/2020/07/23/cet-importing-special-characters-for-non-english-content/](https://ericastockwellalpert.wordpress.com/2020/07/23/cet-importing-special-characters-for-non-english-content/)

**Comment by arunraj777** [comment]
Hi @estockwell-alpert Thank you for your reply. 
Actual Text is 
<img width="534" alt="image" src="https://github.com/estockwell-alpert/ContentExportTool/assets/13220108/23af9a89-02c0-4974-94ef-e45a00e36538">

But it is coming like this
<img width="606" alt="image" src="https://github.com/estockwell-alpert/ContentExportTool/assets/13220108/28349982-cf72-4dde-b499-93ca7ba12f35">

If i try to use Response.BinaryWrite option. All the language values are coming as expected but now I am facing unable to split the data into multiple columns.
Can you give some solution for this.
protected void StartResponse(string fileName)
        {
            Response.Clear();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", string.Format("attachment;filename={0}.csv", fileName));
            Response.Charset = "";
            Response.ContentType = "text/csv";
            Response.ContentEncoding = System.Text.Encoding.UTF32;
            Response.BinaryWrite(System.Text.Encoding.Unicode.GetPreamble());
        }
        protected void SetCookieAndResponse(string responseValue)
        {
            var downloadToken = txtDownloadToken.Value;
            var responseCookie = new HttpCookie("DownloadToken");
            responseCookie.Value = downloadToken;
            responseCookie.HttpOnly = false;
            responseCookie.Expires = DateTime.Now.AddDays(1);
            Response.Cookies.Add(responseCookie);
            Response.Output.Write(responseValue);
            Response.Flush();
            Response.End();
        }

**Comment by estockwell-alpert** [comment]
@arunraj777 I do not have any solution for this because as I said this is a limitation with Excel and what characters it is able to display
